### ISSUE TITLE
Does it support running in WebWorkers?

### ISSUE THREAD

**Issue by purtuga** [rgrove/parse-xml#14]
Does this library work from browser WebWorkers?

I noticed that the retuned value is a. `XmlDocument` instance which I did not think WebWorkers supported it. 

Great work on this library - thanks for sharing it

/Paul

**Comment by rgrove** [comment]
It should work fine. If you try it, let me know!

The [`XmlDocument`](https://github.com/rgrove/parse-xml/blob/613bc8c7706692f323b88923f4e3304a0cfe1d18/src/lib/XmlDocument.js) class is a parse-xml class, not a browser object, so it shouldn't be a problem for Web Workers.

**Comment by jahow** [comment]
I'm using it regularly in a web worker context, can confirm it works flawlessly! Thanks a lot for this amazing lib
