### ISSUE TITLE
Streams

### ISSUE THREAD

**Issue by PabloReszczynski** [rgrove/parse-xml#34]
Hi, great library!
I have a question though, in the documentation it says that this library can support stream-based parsing, but the `xmlParser` constructor only accepts `string` as argument. Any tips on how could I use this library with a `ReadableStream`?

**Comment by PabloReszczynski** [comment]
Oops my bad,

> parse-xml's goal is to be a small, fast, safe, compliant, *non-streaming*, non-validating, browser-friendly parser, because I think this is an under-served niche.

**Comment by rgrove** [comment]
Hey Pablo, thanks for the kind words! And yeah, it sounds like this was just a misunderstanding: as you've noted, parse-xml is specifically _not_ intended to support stream-based parsing. 😄
