### ISSUE TITLE
&#xA; is interpreted as space instead of line feed

### ISSUE THREAD

**Issue by joshtynjala** [rgrove/parse-xml#6]
I have the following element with an attribute.

```
<element attribute="value0&#xA;value1" />
```

`&#xA;` is an encoded line feed, but the parser converts it to a space instead, which is unexpected.

**Comment by rgrove** [comment]
Thanks for reporting this! Looks like this is a bug in the attribute value normalization implementation, which may be because I misinterpreted that portion of the spec. Seems like we should do whitespace normalization _before_ resolving entity references instead of after.

**Comment by rgrove** [comment]
@joshtynjala 👆 That PR should fix the problem. If you get a chance to try it out and let me know how it works for you, that'd be great! Otherwise I'll merge and push a new release tomorrow if I haven't heard from you.

**Comment by joshtynjala** [comment]
Works perfectly! Thanks for the quick response.
